

name: Run RAG Evaluation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      # Suppression de la configuration PostgreSQL, car tu n'en as pas besoin
      - name: Set environment variables
        run: |
          echo "RECOMMENDATIONS_CSV=app/recommendations.csv" >> $GITHUB_ENV  # Chemin vers ton CSV local
          echo "SECRET_KEY= ${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_API_KEY_4= ${{ secrets.AZURE_OPENAI_API_KEY_4 }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_API_ENDPOINT_4= ${{ secrets.OPENAI_API_ENDPOINT_4 }}" >> $GITHUB_ENV
          echo "AZURE_DEPLOYMENT_NAME_4= ${{ secrets.AZURE_DEPLOYMENT_NAME_4 }}" >> $GITHUB_ENV

      
      
      - name: Vérifier les variables d'environnement (sans afficher les valeurs sensibles)
       run: |
          
            echo "SECRET_KEY chargé"
            echo "AZURE_OPENAI_API_KEY_4 chargé"
            echo "AZURE_OPENAI_API_ENDPOINT_4 chargé"
            echo "AZURE_DEPLOYMENT_NAME_4 chargé"
      - name: Run RAG evaluation
        run: pipenv run python app/rag_eval/eval_rag.py
