name: Run Flask Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15  # Assure-toi que la version correspond à celle de ton projet
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $DB_USER"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Charger les variables d'environnement
        run: |
          echo "POSTGRESQL_URI= ${{ secrets.POSTGRESQL_URI }}" >> $GITHUB_ENV 
          echo "DATABASE_URL= ${{ secrets.POSTGRESQL_URI }}" >> $GITHUB_ENV 
          echo "SECRET_KEY= ${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_API_KEY_4= ${{ secrets.AZURE_OPENAI_API_KEY_4 }}" >> $GITHUB_ENV
          echo "AZURE_OPENAI_API_ENDPOINT_4= ${{ secrets.OPENAI_API_ENDPOINT_4 }}" >> $GITHUB_ENV
          echo "AZURE_DEPLOYMENT_NAME_4= ${{ secrets.AZURE_DEPLOYMENT_NAME_4 }}" >> $GITHUB_ENV

      - name: Vérifier les variables d'environnement (sans afficher les valeurs sensibles)
        run: |
          echo "POSTGRESQL_URI chargé"
          echo "DATABASE_URL chargé"
          echo "SECRET_KEY chargé"
          echo "AZURE_OPENAI_API_KEY_4 chargé"
          echo "AZURE_OPENAI_API_ENDPOINT_4 chargé"
          echo "AZURE_DEPLOYMENT_NAME_4 chargé"

      - name: Run tests
        run: pipenv run pytest tests/test_routes.py
