name: Run CVS test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Set environment variables
        run: |
          echo "RECOMMENDATIONS_CSV=app/rag_csv.csv" >> $GITHUB_ENV  # Chemin vers ton CSV local

      - name: Run CVS test
        run: pipenv run pytest tests/test_csv.py