name: Run Flask Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"  # Assure-toi que la version correspond à celle de ton projet

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev  # Installe les dépendances de dev

      - name: Run tests
        run: pipenv run pytest tests/test_routes.py  # Exécute les tests spécifiés
